@startuml Manage Booking (POST)

header Sameple Booking Sequence Diagram
footer Page %page% of %lastpage%
title "Manage Booking (POST)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:booking" as routerBooking
participant "<<controllers>>\n:booking" as controllersBooking
participant "<<model>>\n:Booking" as modelBooking
database "<<MongoDB>>\n:booking" as BookingDatabase

client->server ++:req.post('/campgrounds/:id/booking')
server->routerBooking ++:app.use('/campgrounds',campgrounds)
routerBooking -> controllersBooking ++:addBooking()
controllersBooking->modelBooking ++:create(req.body)
modelBooking ->BookingDatabase ++: BookingSchema
BookingDatabase --> modelBooking --: booking
controllersBooking <-- modelBooking --:booking
controllersBooking->client --:response

@enduml
